### ISSUE TITLE
`Guesser` can crash on inaccurate rounding

### ISSUE THREAD

**Issue by SouthEndMusic** [SciML/FindFirstFunctions.jl#25]
In the rounding in for `linear_lookup`, this line can crash with an `InexactError`:

https://github.com/SciML/FindFirstFunctions.jl/blob/9f69a2d0779410cd58e20cf7396c4a9ffea86448/src/FindFirstFunctions.jl#L243

This is presumably if the second argument float is too big to be rounded to any particular integer given its precision. I propose falling back to `idx_prev[]` in this case.

**Comment by DaniGlez** [comment]
Would it make sense to use `typemax` (maybe `typemin`, respectively) or `lastindex` in that case instead?

**Comment by SouthEndMusic** [comment]
Ah that makes sense
